version: "3.8"

services:
  postgres:
    image: postgres:17.5
    container_name: product_crud_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:

networks:
  default:
    name: product_crud