basePath: /
definitions:
  product.CreateRequest:
    properties:
      name:
        type: string
      price:
        type: number
    type: object
  product.CreateResponse:
    properties:
      id:
        type: string
    type: object
  product.DeleteResponse:
    properties:
      id:
        type: string
    type: object
  product.FetchByIdResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  product.FetchPagedProductsResponse:
    properties:
      products:
        items:
          $ref: '#/definitions/product.ProductResponse'
        type: array
    type: object
  product.ProductResponse:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  product.UpdateRequest:
    properties:
      id:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  product.UpdateResponse:
    properties:
      id:
        type: string
    type: object
  user.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.LoginResponse:
    properties:
      access_token:
        type: string
    type: object
  user.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  user.RegisterResponse:
    properties:
      id:
        type: string
    type: object
  web.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:7000
info:
  contact:
    email: support@swagger.io
    name: product_crud API Support
    url: http://www.swagger.io/support
  description: |-
    product_crud is an API for managing users and products.
    It provides authentication endpoints and a product catalog with CRUD operations.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: product_crud API
  version: "1.0"
paths:
  /products:
    delete:
      consumes:
      - application/json
      description: Permanently delete a product by its ID
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.DeleteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/web.errorResponse'
      security:
      - Bearer: []
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Retrieve a paginated list of products with optional sorting
      parameters:
      - description: pageNumber
        in: query
        name: pageNumber
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      - description: sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.FetchPagedProductsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/web.errorResponse'
      security:
      - Bearer: []
      summary: List products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product with a name and price
      parameters:
      - description: CreateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/product.CreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/product.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/web.errorResponse'
      security:
      - Bearer: []
      summary: Create a new product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product details (name and price)
      parameters:
      - description: UpdateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/product.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.UpdateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/web.errorResponse'
      security:
      - Bearer: []
      summary: Update an existing product
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve details of a single product by its ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.FetchByIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      security:
      - Bearer: []
      summary: Get product by ID
      tags:
      - products
  /users/login:
    post:
      consumes:
      - application/json
      description: Validates user credentials and returns a JWT token
      parameters:
      - description: LoginRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Authenticate a user
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: Creates a new user with name, email, and password
      parameters:
      - description: RegisterRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: Register a new user
      tags:
      - Users
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
